### DISCUSSION TITLE
Some question. (or maybe FaQ?)

### DISCUSSION THREAD

**Discussion by Scoooolzs** [games647/FastLogin#778] [Q&A] [answered]
Hi, i have some question:

1. Are FastLogin will have a reload config soon?
2. People says: "AuthMe and FastLogin will easy to exploit. Because the plugin is free.", Is that true?
3. Are FastLogin will have a backup data soon?
4. Are FastLogin will have a run a command in console soon? Like:
```yml
run: 
  premium:
    - "[CONSOLE] title %player% subtitle \"You have logged in using a premium account.\"" # i forgot you can using "[TITLE]" and "[SUBTITLE]"
    - "[MESSAGE]" You have logged in!"
```
5. Will this owner of FastLogin create some Auth Plugin? (I'm out of ideas lol)

That's it!
Maybe i will send more question soon.
