### ISSUE TITLE
Tunnelled server connection -> Invalid Session

### ISSUE THREAD

**Issue by Enginecrafter77** [games647/FastLogin#810]
### What happened?

Basically, I tried installing FastLogin, ProtocolLib and LoginSecurity on my server. The server has run in online mode before, so I needed FastLogin in order to switch to offline mode (what I mean by that that I enabled premiumUuids so the UUIDs stay the same for the original players).

I run the server on a machine in my local network. But I can't easily just forward ports to this machine. So I used my other (public-facing) VPS to act as a routing reverse proxy for my server.

Basically, my setup looks like this.

Player ---> Proxy server <==(10.25.25.1)==[OpenVPN Tunnel]==(10.25.25.2)==> Minecraft Server

The proxy server does not run any minecraft-related software. All it does is run OpenVPN server (to which the MC server connects to). Additionally, to achieve the port forwarding, I used the following iptables rules:

```
iptables -t nat -A PREROUTING -p tcp --dport 25565 -j DNAT --to-destination 10.25.25.2:25565
iptables -t nat -A POSTROUTING -p tcp --dport 25565 -j MASQUERADE
```

To the actually relevant part. While the server runs in online mode, everything works flawlessly. When I installed FastLogin and LoginSecurity, none of my friends could log in. They all received the "Invalid Session" message. What's more interesting is that I was able to log in just fine using the same tunnelled connection.

On a side note, I run the server in pufferpanel running thorough docker. AFAIK docker also does it's own routing so that might also be an issue.

I also tried debugging the plugin through IntelliJ IDEA, but there everything worked just fine. I even tried to have it use the same VPN tunnel, and it worked as expected.

Honestly, I don't know what to do, I was just hoping you might have more insight in the role routing plays in the protocol (i.e. if the SNAT has some negative impact or something like that).

### What did you expect?

I expected the tunnel to work fine, just like it used in online mode.

### Steps to reproduce

On machine A (facing internet):
1. Setup OpenVPN server with `ifconfig 10.25.25.1 10.25.25.2` directive
2. Setup the iptables rules:
    ```
    iptables -t nat -A PREROUTING -p tcp --dport 25565 -j DNAT --to-destination 10.25.25.2:25565
    iptables -t nat -A POSTROUTING -p tcp --dport 25565 -j MASQUERADE
    ```

On machine B:
1. Setup OpenVPN client to Machine A with `ifconfig 10.25.25.2 10.25.25.1`
3. Install docker and docker-compose
4. Create `docker-compose.yml`
    ```
    version: '3.8'

    services:
      pufferpanel:
        container_name: puffer
        image: pufferpanel/pufferpanel:java
        volumes:
          - ./puffer-data:/var/lib/pufferpanel
          - ./puffer-config:/etc/pufferpanel
        ports:
          - "8080:8080"
          - "25565:25565"
    ```
5. Start the container (`docker-compose up -d`)
6. Install the minecraft server using pufferpanel (use the provided template for spigot)
7. Install all the plugins mentioned below
8. Use the provided config for FastLogin
9. Use the following config for LoginSecurity (minimized):
    ```
    register:
      required: true
      captcha: false
      confirm-password: false
    login:
      max-tries: 5
      username-match-exact: true
    password:
      min-length: 6
    password-max-length: 32
    join:
      blindness: true
      location: SPAWN
      hide-inventory: true
      hide-inventory-safe: false
    username:
      filter-special-chars: true
      min-length: 3
      max-length: 16
    command-shortcut:
      enabled: false
      login: /l
      register: /reg
    updater:
      enabled: false
      channel: BETA
    session-timeout: -1
    login-timeout: 120
    login-message-delay: 10
    language: en_us
    ```
11. Change the `settings/timeout-time` in spigot.yml to 80 (With the default 60 spigot watchdog thread throws errors on stop)
12. Start the server through pufferpanel

NOTE: This is just a rough guide on how I set up the server, but it does not guarantee the bug can be reproduced, as even I wasn't able to reproduce it reliably.

### Plugin list

ProtocolLib, CrisTreeCapitator, FastLogin, LoginSecurity, ServerBackup

### Configuration file

https://www.toptal.com/developers/hastebin/figacelabi.yaml

### Server log

```shell
https://www.toptal.com/developers/hastebin/tisizewaba.yaml
```

### Plugin version

1075

### Platform

Spigot

### Relevance

- [X] I tried the latest build (build refers to development builds not necessary a release version)
- [X] I checked for existing tickets -
If there are, please vote them with a thumps reaction and not create new ones
